---
apiVersion: v1
kind: Service
metadata:
  name: flask-mysql
  labels:
    app: flaskapp
spec:
  ports:
    - port: 3306
  selector:
    app: flaskapp
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: flask-nginx
  labels:
    app: flaskapp
spec:
  type: LoadBalancer
  selector:
    app: flaskapp
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: flask-uwsgi
  labels:
    app: flaskapp
spec:
  ports:
    - port: 8001
  selector:
    app: flaskapp
  clusterIP: None